title: "mCPT at SemEval-2023 Task 3"
description: >- # this means to ignore newlines until "baseurl:"
  SemEval'23
# Build settings
remote_theme: socialcomplab/cayman
github:
  parent: https://socialcomplab.github.io/
