name: semenv
dependencies:
- python==3.10
- pytorch
- transformers
- numpy
- scipy
- pandas
- matplotlib
- execnb
- scikit-learn
- torchmetrics
- seaborn
- sentence-transformers>=2.2.2
# Hp Opt & analysis
- optuna
- plotly
- umap-learn
